name: Setup Requirements

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: '3.11'
      install-azure-cli:
        required: false
        type: boolean
        default: false

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'
      
      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install aiohttp==3.9.1 psutil==5.9.6 tabulate==0.9.0
          
          # Optional performance improvements
          pip install uvloop==0.19.0 || true
          pip install aiodns==3.1.1 || true
          pip install cchardet==2.1.7 || true
      
      - name: Install Azure CLI
        if: inputs.install-azure-cli
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az version
      
      - name: Apply System Optimizations
        run: |
          # Increase file descriptor limits
          sudo sysctl -w fs.file-max=2097152 || true
          sudo sysctl -w fs.nr_open=2097152 || true
          
          # Network optimizations
          sudo sysctl -w net.core.somaxconn=65535 || true
          sudo sysctl -w net.ipv4.tcp_max_syn_backlog=65535 || true
          sudo sysctl -w net.core.netdev_max_backlog=65535 || true
          sudo sysctl -w net.ipv4.tcp_tw_reuse=1 || true
          sudo sysctl -w net.ipv4.tcp_fin_timeout=15 || true
          sudo sysctl -w net.ipv4.ip_local_port_range="1024 65535" || true
          
          # Set ulimits
          ulimit -n 65536 || true
          ulimit -u 32768 || true
          
          echo "System optimizations applied"